apiVersion: apps/v1
kind: Deployment
metadata:
  name: document-service
  labels:
    app: document-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: document-service
  template:
    metadata:
      labels:
        app: document-service
    spec:
      containers:
      - name: document-service
        image: document-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: document-service-secret
              key: database_url
        - name: DEBUG
          value: "0"
        - name: ALLOWED_HOSTS
          value: "*"
        volumeMounts:
        - name: media-storage
          mountPath: /app/media
      volumes:
      - name: media-storage
        persistentVolumeClaim:
          claimName: document-service-media-pvc