apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: document-service-media-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard